services:

  database:
    image: mysql:8
    command: --init-file /data/application/init.sql
    volumes:
      - ./database/init.sql:/data/application/init.sql
    networks:
      - networkName
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: database
      #MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: Root@123
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  core-server:
    build: ./clustered-data-warehouse
    depends_on:
      database:
        condition: service_healthy
    networks:
      - networkName
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/mnasro?autoReconnect=false&useSSL=true
    ports:
      - 8080:8080

networks:
  networkName: